// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class BookPageReferenceConfiguration : IEntityTypeConfiguration<BookPageReference>
    {
        public void Configure(EntityTypeBuilder<BookPageReference> entity)
        {
            entity.ToTable("BOOK_PAGE_REFERENCE");

            entity.Property(e => e.BookPageReferenceId).HasColumnName("BOOK_PAGE_REFERENCE_ID");
            entity.Property(e => e.Book)
            .HasMaxLength(10)
            .IsUnicode(false)
            .IsFixedLength()
            .HasColumnName("BOOK");
            entity.Property(e => e.BookSuffix)
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasColumnName("BOOK_SUFFIX");
            entity.Property(e => e.CreateDate)
            .HasColumnType("datetime")
            .HasColumnName("CREATE_DATE");
            entity.Property(e => e.ImageBatchDocumentReferenceId).HasColumnName("IMAGE_BATCH_DOCUMENT_REFERENCE_ID");
            entity.Property(e => e.Page)
            .HasMaxLength(10)
            .IsUnicode(false)
            .IsFixedLength()
            .HasColumnName("PAGE");
            entity.Property(e => e.PageSuffix)
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasColumnName("PAGE_SUFFIX");
            entity.Property(e => e.Source)
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasColumnName("SOURCE");
            entity.Property(e => e.UpdateDate)
            .HasColumnType("datetime")
            .HasColumnName("UPDATE_DATE");

            entity.HasOne(d => d.ImageBatchDocumentReference).WithMany(p => p.BookPageReference)
            .HasForeignKey(d => d.ImageBatchDocumentReferenceId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_BOOK_PAGE_REFERENCE_IMAGE_BATCH_DOCUMENT_REFERENCE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BookPageReference> entity);
    }
}
