// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class ClerkNumberTrackingConfiguration : IEntityTypeConfiguration<ClerkNumberTracking>
    {
        public void Configure(EntityTypeBuilder<ClerkNumberTracking> entity)
        {
            entity
            .HasNoKey()
            .ToTable("ClerkNumberTracking", "CDC");

            entity.Property(e => e.ClerkNumber)
            .IsRequired()
            .HasMaxLength(14)
            .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ClerkNumberTracking> entity);
    }
}
