// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class CngapListConfiguration : IEntityTypeConfiguration<CngapList>
    {
        public void Configure(EntityTypeBuilder<CngapList> entity)
        {
            entity
            .HasNoKey()
            .ToTable("CNGapList", "CDC");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CngapList> entity);
    }
}
