// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class CountyConfiguration : IEntityTypeConfiguration<County>
    {
        public void Configure(EntityTypeBuilder<County> entity)
        {
            entity.ToTable("COUNTY");

            entity.Property(e => e.CountyId)
            .ValueGeneratedOnAdd()
            .HasColumnName("COUNTY_ID");
            entity.Property(e => e.CountyCode)
            .HasMaxLength(3)
            .IsUnicode(false)
            .IsFixedLength()
            .HasColumnName("COUNTY_CODE");
            entity.Property(e => e.CountyName)
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasColumnName("COUNTY_NAME");
            entity.Property(e => e.CreateDate)
            .HasColumnType("datetime")
            .HasColumnName("CREATE_DATE");
            entity.Property(e => e.DataCenterId).HasColumnName("DATA_CENTER_ID");
            entity.Property(e => e.IsActive).HasColumnName("IS_ACTIVE");
            entity.Property(e => e.Priority).HasColumnName("PRIORITY");
            entity.Property(e => e.UpdateDate)
            .HasColumnType("datetime")
            .HasColumnName("UPDATE_DATE");

            entity.HasOne(d => d.DataCenter).WithMany(p => p.County)
            .HasForeignKey(d => d.DataCenterId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_COUNTY_DATA_CENTER");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<County> entity);
    }
}
