// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class DataCenterConfiguration : IEntityTypeConfiguration<DataCenter>
    {
        public void Configure(EntityTypeBuilder<DataCenter> entity)
        {
            entity.ToTable("DATA_CENTER");

            entity.Property(e => e.DataCenterId).HasColumnName("DATA_CENTER_ID");
            entity.Property(e => e.Code)
            .HasMaxLength(4)
            .IsUnicode(false)
            .HasColumnName("CODE");
            entity.Property(e => e.Name)
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasColumnName("NAME");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DataCenter> entity);
    }
}
