// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class DateOfFileConfiguration : IEntityTypeConfiguration<DateOfFile>
    {
        public void Configure(EntityTypeBuilder<DateOfFile> entity)
        {
            entity.HasKey(e => e.DateOfFileId).HasName("PK_DateOfFile");

            entity.ToTable("DATE_OF_FILE");

            entity.Property(e => e.DateOfFileId).HasColumnName("DATE_OF_FILE_ID");
            entity.Property(e => e.CountyId).HasColumnName("COUNTY_ID");
            entity.Property(e => e.CreateDate)
            .HasColumnType("datetime")
            .HasColumnName("CREATE_DATE");
            entity.Property(e => e.Date)
            .HasColumnType("datetime")
            .HasColumnName("DATE");
            entity.Property(e => e.IsCertified)
            .HasDefaultValueSql("('False')")
            .HasColumnName("IS_CERTIFIED");
            entity.Property(e => e.IsDataCenterSuccessful)
            .HasDefaultValueSql("('False')")
            .HasColumnName("IS_DATA_CENTER_SUCCESSFUL");
            entity.Property(e => e.IsOverallSuccessful)
            .HasDefaultValueSql("('False')")
            .HasColumnName("IS_OVERALL_SUCCESSFUL");
            entity.Property(e => e.UpdateDate)
            .HasColumnType("datetime")
            .HasColumnName("UPDATE_DATE");

            entity.HasOne(d => d.County).WithMany(p => p.DateOfFile)
            .HasForeignKey(d => d.CountyId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_COUNTY_DATE_OF_FILE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DateOfFile> entity);
    }
}
