// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class DocumentDescriptionConfiguration : IEntityTypeConfiguration<DocumentDescription>
    {
        public void Configure(EntityTypeBuilder<DocumentDescription> entity)
        {
            entity.HasKey(e => e.DocumentDescriptionId).HasName("PK_DOCUMENT_DESCRIPTIONS");

            entity.ToTable("DOCUMENT_DESCRIPTION");

            entity.Property(e => e.DocumentDescriptionId).HasColumnName("DOCUMENT_DESCRIPTION_ID");
            entity.Property(e => e.BatchId).HasColumnName("BATCH_ID");
            entity.Property(e => e.County)
            .IsRequired()
            .HasMaxLength(20)
            .IsUnicode(false)
            .HasColumnName("COUNTY");
            entity.Property(e => e.CreateDate)
            .HasColumnType("datetime")
            .HasColumnName("CREATE_DATE");
            entity.Property(e => e.DateOfFile)
            .HasColumnType("datetime")
            .HasColumnName("DATE_OF_FILE");
            entity.Property(e => e.PrimaryReference)
            .HasMaxLength(20)
            .IsUnicode(false)
            .HasColumnName("PRIMARY_REFERENCE");
            entity.Property(e => e.SecondaryReference)
            .HasMaxLength(20)
            .IsUnicode(false)
            .HasColumnName("SECONDARY_REFERENCE");
            entity.Property(e => e.State)
            .IsRequired()
            .HasMaxLength(2)
            .IsUnicode(false)
            .IsFixedLength()
            .HasColumnName("STATE");
            entity.Property(e => e.UpdateDate)
            .HasColumnType("datetime")
            .HasColumnName("UPDATE_DATE");

            entity.HasOne(d => d.Batch).WithMany(p => p.DocumentDescription)
            .HasForeignKey(d => d.BatchId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_DOCUMENT_DESCRIPTION_BATCH");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DocumentDescription> entity);
    }
}
