// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class DocumentDescriptionRcvdConfiguration : IEntityTypeConfiguration<DocumentDescriptionRcvd>
    {
        public void Configure(EntityTypeBuilder<DocumentDescriptionRcvd> entity)
        {
            entity.ToTable("DOCUMENT_DESCRIPTION_RCVD");

            entity.Property(e => e.DocumentDescriptionRcvdId).HasColumnName("DOCUMENT_DESCRIPTION_RCVD_ID");
            entity.Property(e => e.CreateDate)
            .HasColumnType("datetime")
            .HasColumnName("CREATE_DATE");
            entity.Property(e => e.DateReceived)
            .HasColumnType("datetime")
            .HasColumnName("DATE_RECEIVED");
            entity.Property(e => e.DocumentDescriptionId).HasColumnName("DOCUMENT_DESCRIPTION_ID");
            entity.Property(e => e.ImageBatchId)
            .HasDefaultValueSql("((1))")
            .HasColumnName("IMAGE_BATCH_ID");
            entity.Property(e => e.UpdateDate)
            .HasColumnType("datetime")
            .HasColumnName("UPDATE_DATE");

            entity.HasOne(d => d.DocumentDescription).WithMany(p => p.DocumentDescriptionRcvd)
            .HasForeignKey(d => d.DocumentDescriptionId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_DOCUMENT_DESCRIPTION_RCVD_DOCUMENT_DESCRIPTION");

            entity.HasOne(d => d.ImageBatch).WithMany(p => p.DocumentDescriptionRcvd)
            .HasForeignKey(d => d.ImageBatchId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_IMAGE_BATCH_DOCUMENT_DESCRIPTION_RCVD");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DocumentDescriptionRcvd> entity);
    }
}
