// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class ErrorDescriptionConfiguration : IEntityTypeConfiguration<ErrorDescription>
    {
        public void Configure(EntityTypeBuilder<ErrorDescription> entity)
        {
            entity.HasKey(e => e.ErrorDescriptionId).HasName("PK_ERROR_DESCRIPTIONS");

            entity.ToTable("ERROR_DESCRIPTION");

            entity.Property(e => e.ErrorDescriptionId).HasColumnName("ERROR_DESCRIPTION_ID");
            entity.Property(e => e.Code)
            .IsRequired()
            .HasMaxLength(3)
            .IsUnicode(false)
            .IsFixedLength()
            .HasColumnName("CODE");
            entity.Property(e => e.CreateDate)
            .HasColumnType("datetime")
            .HasColumnName("CREATE_DATE");
            entity.Property(e => e.ErrorType)
            .IsRequired()
            .HasMaxLength(1)
            .IsUnicode(false)
            .IsFixedLength()
            .HasColumnName("ERROR_TYPE");
            entity.Property(e => e.Message)
            .IsRequired()
            .IsUnicode(false)
            .HasColumnName("MESSAGE");
            entity.Property(e => e.UpdateDate)
            .HasColumnType("datetime")
            .HasColumnName("UPDATE_DATE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ErrorDescription> entity);
    }
}
