// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class EventTypeConfiguration : IEntityTypeConfiguration<EventType>
    {
        public void Configure(EntityTypeBuilder<EventType> entity)
        {
            entity.HasKey(e => e.EventTypeCode);

            entity.ToTable("EVENT_TYPE", "DCW");

            entity.Property(e => e.EventTypeCode)
            .HasMaxLength(10)
            .IsUnicode(false)
            .HasColumnName("EVENT_TYPE_CODE");
            entity.Property(e => e.EventTypeDescription)
            .IsRequired()
            .HasMaxLength(200)
            .IsUnicode(false)
            .HasColumnName("EVENT_TYPE_DESCRIPTION");
            entity.Property(e => e.ExpectedProductivity).HasColumnName("EXPECTED_PRODUCTIVITY");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EventType> entity);
    }
}
