// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class EventConfiguration : IEntityTypeConfiguration<Event>
    {
        public void Configure(EntityTypeBuilder<Event> entity)
        {
            entity.ToTable("EVENT", "DCW");

            entity.Property(e => e.EventId).HasColumnName("EVENT_ID");
            entity.Property(e => e.CountyId).HasColumnName("COUNTY_ID");
            entity.Property(e => e.DateOfFileId).HasColumnName("DATE_OF_FILE_ID");
            entity.Property(e => e.EventTypeCode)
            .IsRequired()
            .HasMaxLength(10)
            .IsUnicode(false)
            .HasColumnName("EVENT_TYPE_CODE");
            entity.Property(e => e.Priority).HasColumnName("PRIORITY");
            entity.Property(e => e.ReportFileName)
            .IsRequired()
            .HasMaxLength(250)
            .IsUnicode(false)
            .HasColumnName("REPORT_FILE_NAME");

            entity.HasOne(d => d.County).WithMany(p => p.Event)
            .HasForeignKey(d => d.CountyId)
            .HasConstraintName("FK_EVENT_COUNTY");

            entity.HasOne(d => d.DateOfFile).WithMany(p => p.Event)
            .HasForeignKey(d => d.DateOfFileId)
            .HasConstraintName("FK_DATE_OF_FILE_EVENT");

            entity.HasOne(d => d.EventTypeCodeNavigation).WithMany(p => p.Event)
            .HasForeignKey(d => d.EventTypeCode)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_EVENT_TYPE_EVENT");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Event> entity);
    }
}
