// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class ImageBatchFtpUploadConfiguration : IEntityTypeConfiguration<ImageBatchFtpUpload>
    {
        public void Configure(EntityTypeBuilder<ImageBatchFtpUpload> entity)
        {
            entity.ToTable("IMAGE_BATCH_FTP_UPLOAD");

            entity.Property(e => e.ImageBatchFtpUploadId).HasColumnName("IMAGE_BATCH_FTP_UPLOAD_ID");
            entity.Property(e => e.CountyFtpPathId).HasColumnName("COUNTY_FTP_PATH_ID");
            entity.Property(e => e.CreateDate)
            .HasColumnType("datetime")
            .HasColumnName("CREATE_DATE");
            entity.Property(e => e.FtpUploadDate)
            .HasColumnType("datetime")
            .HasColumnName("FTP_UPLOAD_DATE");
            entity.Property(e => e.ImageBatchId).HasColumnName("IMAGE_BATCH_ID");
            entity.Property(e => e.UpdateDate)
            .HasColumnType("datetime")
            .HasColumnName("UPDATE_DATE");

            entity.HasOne(d => d.ImageBatch).WithMany(p => p.ImageBatchFtpUpload)
            .HasForeignKey(d => d.ImageBatchId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_IMAGE_BATCH_IMAGE_BATCH_FTP_UPLOAD");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ImageBatchFtpUpload> entity);
    }
}
