// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class ImageBatchDocumentReferenceConfiguration : IEntityTypeConfiguration<ImageBatchDocumentReference>
    {
        public void Configure(EntityTypeBuilder<ImageBatchDocumentReference> entity)
        {
            entity.ToTable("IMAGE_BATCH_DOCUMENT_REFERENCE");

            entity.Property(e => e.ImageBatchDocumentReferenceId).HasColumnName("IMAGE_BATCH_DOCUMENT_REFERENCE_ID");
            entity.Property(e => e.CreateDate)
            .HasColumnType("datetime")
            .HasColumnName("CREATE_DATE");
            entity.Property(e => e.UpdateDate)
            .HasColumnType("datetime")
            .HasColumnName("UPDATE_DATE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ImageBatchDocumentReference> entity);
    }
}
