// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class NonWeekendHolidayConfiguration : IEntityTypeConfiguration<NonWeekendHoliday>
    {
        public void Configure(EntityTypeBuilder<NonWeekendHoliday> entity)
        {
            entity.ToTable("NON_WEEKEND_HOLIDAY");

            entity.Property(e => e.NonWeekendHolidayId).HasColumnName("NON_WEEKEND_HOLIDAY_ID");
            entity.Property(e => e.CreateDate)
            .HasColumnType("datetime")
            .HasColumnName("CREATE_DATE");
            entity.Property(e => e.Holiday)
            .HasColumnType("datetime")
            .HasColumnName("HOLIDAY");
            entity.Property(e => e.ProcessingUnitId).HasColumnName("PROCESSING_UNIT_ID");
            entity.Property(e => e.UpdateDate)
            .HasColumnType("datetime")
            .HasColumnName("UPDATE_DATE");

            entity.HasOne(d => d.ProcessingUnit).WithMany(p => p.NonWeekendHoliday)
            .HasForeignKey(d => d.ProcessingUnitId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_NON_WEEKEND_HOLIDAY_PROCESSING_UNIT");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<NonWeekendHoliday> entity);
    }
}
