// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class OnDemandReportConfiguration : IEntityTypeConfiguration<OnDemandReport>
    {
        public void Configure(EntityTypeBuilder<OnDemandReport> entity)
        {
            entity.HasKey(e => e.OnDemandReportId).HasName("PK_ON_DEMAMD_REPORT");

            entity.ToTable("ON_DEMAND_REPORT");

            entity.Property(e => e.OnDemandReportId)
            .ValueGeneratedNever()
            .HasColumnName("ON_DEMAND_REPORT_ID");
            entity.Property(e => e.CreateDate)
            .HasColumnType("datetime")
            .HasColumnName("CREATE_DATE");
            entity.Property(e => e.ReportName)
            .IsRequired()
            .HasMaxLength(100)
            .IsUnicode(false)
            .HasColumnName("REPORT_NAME");
            entity.Property(e => e.SourceFileKey)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasColumnName("SOURCE_FILE_KEY");
            entity.Property(e => e.UpdateDate)
            .HasColumnType("datetime")
            .HasColumnName("UPDATE_DATE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OnDemandReport> entity);
    }
}
