// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class PerformanceTargetConfiguration : IEntityTypeConfiguration<PerformanceTarget>
    {
        public void Configure(EntityTypeBuilder<PerformanceTarget> entity)
        {
            entity.ToTable("PERFORMANCE_TARGET");

            entity.Property(e => e.PerformanceTargetId).HasColumnName("PERFORMANCE_TARGET_ID");
            entity.Property(e => e.CountyId).HasColumnName("COUNTY_ID");
            entity.Property(e => e.CreateDate)
            .HasColumnType("datetime")
            .HasColumnName("CREATE_DATE");
            entity.Property(e => e.IsActive).HasColumnName("IS_ACTIVE");
            entity.Property(e => e.NumberOfHours).HasColumnName("NUMBER_OF_HOURS");
            entity.Property(e => e.ProcessingUnitId).HasColumnName("PROCESSING_UNIT_ID");
            entity.Property(e => e.UpdateDate)
            .HasColumnType("datetime")
            .HasColumnName("UPDATE_DATE");

            entity.HasOne(d => d.County).WithMany(p => p.PerformanceTarget)
            .HasForeignKey(d => d.CountyId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_PERFORMANCE_TARGET_COUNTY");

            entity.HasOne(d => d.ProcessingUnit).WithMany(p => p.PerformanceTarget)
            .HasForeignKey(d => d.ProcessingUnitId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_PERFORMANCE_TARGET_PROCESSING_UNIT");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PerformanceTarget> entity);
    }
}
