// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class PostingAttemptConfiguration : IEntityTypeConfiguration<PostingAttempt>
    {
        public void Configure(EntityTypeBuilder<PostingAttempt> entity)
        {
            entity.HasKey(e => e.PostingAttemptId).HasName("PK_POSTING_ATTEMPTS");

            entity.ToTable("POSTING_ATTEMPT");

            entity.Property(e => e.PostingAttemptId).HasColumnName("POSTING_ATTEMPT_ID");
            entity.Property(e => e.CorrelationId)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasColumnName("CORRELATION_ID");
            entity.Property(e => e.CreateDate)
            .HasColumnType("datetime")
            .HasColumnName("CREATE_DATE");
            entity.Property(e => e.DocumentDescriptionId).HasColumnName("DOCUMENT_DESCRIPTION_ID");
            entity.Property(e => e.PostingAttemptStatusId).HasColumnName("POSTING_ATTEMPT_STATUS_ID");
            entity.Property(e => e.UpdateDate)
            .HasColumnType("datetime")
            .HasColumnName("UPDATE_DATE");

            entity.HasOne(d => d.DocumentDescription).WithMany(p => p.PostingAttempt)
            .HasForeignKey(d => d.DocumentDescriptionId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_POSTING_ATTEMPT_DOCUMENT_DESCRIPTION");

            entity.HasOne(d => d.PostingAttemptStatus).WithMany(p => p.PostingAttempt)
            .HasForeignKey(d => d.PostingAttemptStatusId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_POSTING_ATTEMPT_POSTING_ATTEMPT_STATUS");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PostingAttempt> entity);
    }
}
