// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class PostingAttemptStatusConfiguration : IEntityTypeConfiguration<PostingAttemptStatus>
    {
        public void Configure(EntityTypeBuilder<PostingAttemptStatus> entity)
        {
            entity.ToTable("POSTING_ATTEMPT_STATUS");

            entity.Property(e => e.PostingAttemptStatusId).HasColumnName("POSTING_ATTEMPT_STATUS_ID");
            entity.Property(e => e.Description)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasColumnName("DESCRIPTION");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PostingAttemptStatus> entity);
    }
}
