// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class PostingResultConfiguration : IEntityTypeConfiguration<PostingResult>
    {
        public void Configure(EntityTypeBuilder<PostingResult> entity)
        {
            entity.HasKey(e => e.PostingResultId).HasName("PK_POSTING_RESULTS");

            entity.ToTable("POSTING_RESULT");

            entity.Property(e => e.PostingResultId).HasColumnName("POSTING_RESULT_ID");
            entity.Property(e => e.CreateDate)
            .HasColumnType("datetime")
            .HasColumnName("CREATE_DATE");
            entity.Property(e => e.PostingAttemptId).HasColumnName("POSTING_ATTEMPT_ID");
            entity.Property(e => e.Status)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasColumnName("STATUS");
            entity.Property(e => e.UpdateDate)
            .HasColumnType("datetime")
            .HasColumnName("UPDATE_DATE");

            entity.HasOne(d => d.PostingAttempt).WithMany(p => p.PostingResult)
            .HasForeignKey(d => d.PostingAttemptId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_POSTING_RESULTS_POSTING_ATTEMPTS");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PostingResult> entity);
    }
}
