// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class PostingResultErrorDetailConfiguration : IEntityTypeConfiguration<PostingResultErrorDetail>
    {
        public void Configure(EntityTypeBuilder<PostingResultErrorDetail> entity)
        {
            entity.HasKey(e => e.PostingResultsErrorDetailId).HasName("PK_POSTING_RESULTS_ERROR_DETAILS");

            entity.ToTable("POSTING_RESULT_ERROR_DETAIL");

            entity.Property(e => e.PostingResultsErrorDetailId).HasColumnName("POSTING_RESULTS_ERROR_DETAIL_ID");
            entity.Property(e => e.CreateDate)
            .HasColumnType("datetime")
            .HasColumnName("CREATE_DATE");
            entity.Property(e => e.ErrorDescriptionId).HasColumnName("ERROR_DESCRIPTION_ID");
            entity.Property(e => e.PostingResultId).HasColumnName("POSTING_RESULT_ID");
            entity.Property(e => e.UpdateDate)
            .HasColumnType("datetime")
            .HasColumnName("UPDATE_DATE");

            entity.HasOne(d => d.ErrorDescription).WithMany(p => p.PostingResultErrorDetail)
            .HasForeignKey(d => d.ErrorDescriptionId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_POSTING_RESULTS_ERROR_DETAILS_ERROR_DESCRIPTIONS1");

            entity.HasOne(d => d.PostingResult).WithMany(p => p.PostingResultErrorDetail)
            .HasForeignKey(d => d.PostingResultId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_POSTING_RESULTS_ERROR_DETAILS_POSTING_RESULTS");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PostingResultErrorDetail> entity);
    }
}
