// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class ProcessingUnitConfiguration : IEntityTypeConfiguration<ProcessingUnit>
    {
        public void Configure(EntityTypeBuilder<ProcessingUnit> entity)
        {
            entity.ToTable("PROCESSING_UNIT");

            entity.Property(e => e.ProcessingUnitId).HasColumnName("PROCESSING_UNIT_ID");
            entity.Property(e => e.CreateDate)
            .HasColumnType("datetime")
            .HasColumnName("CREATE_DATE");
            entity.Property(e => e.ProcessingUnitCode)
            .IsRequired()
            .HasMaxLength(10)
            .IsUnicode(false)
            .HasColumnName("PROCESSING_UNIT_CODE");
            entity.Property(e => e.ProcessingUnitName)
            .IsRequired()
            .HasMaxLength(100)
            .IsUnicode(false)
            .HasColumnName("PROCESSING_UNIT_NAME");
            entity.Property(e => e.UpdateDate)
            .HasColumnType("datetime")
            .HasColumnName("UPDATE_DATE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProcessingUnit> entity);
    }
}
