// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class TaskDetailBlobConfiguration : IEntityTypeConfiguration<TaskDetailBlob>
    {
        public void Configure(EntityTypeBuilder<TaskDetailBlob> entity)
        {
            entity
            .HasNoKey()
            .ToTable("TASK_DETAIL_BLOB", "DCW");

            entity.Property(e => e.TaskDetail)
            .IsRequired()
            .HasColumnName("TASK_DETAIL");
            entity.Property(e => e.TaskDetailId).HasColumnName("TASK_DETAIL_ID");

            entity.HasOne(d => d.TaskDetailNavigation).WithMany()
            .HasForeignKey(d => d.TaskDetailId)
            .HasConstraintName("FK_TASK_DETAIL_TASK_DETAIL_BLOB");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TaskDetailBlob> entity);
    }
}
