// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class TaskTypeConfiguration : IEntityTypeConfiguration<TaskType>
    {
        public void Configure(EntityTypeBuilder<TaskType> entity)
        {
            entity.HasKey(e => e.TaskTypeCode);

            entity.ToTable("TASK_TYPE", "DCW");

            entity.Property(e => e.TaskTypeCode)
            .HasMaxLength(10)
            .IsUnicode(false)
            .HasColumnName("TASK_TYPE_CODE");
            entity.Property(e => e.Selectable).HasColumnName("SELECTABLE");
            entity.Property(e => e.TaskTypeDescription)
            .IsRequired()
            .HasMaxLength(200)
            .IsUnicode(false)
            .HasColumnName("TASK_TYPE_DESCRIPTION");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TaskType> entity);
    }
}
