// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class TempDeleteTasksConfiguration : IEntityTypeConfiguration<TempDeleteTasks>
    {
        public void Configure(EntityTypeBuilder<TempDeleteTasks> entity)
        {
            entity
            .HasNoKey()
            .ToTable("TEMP_DELETE_TASKS");

            entity.Property(e => e.Reference)
            .HasMaxLength(255)
            .IsUnicode(false)
            .HasColumnName("reference");
            entity.Property(e => e.TaskId).HasColumnName("task_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TempDeleteTasks> entity);
    }
}
