// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class UserEventConfiguration : IEntityTypeConfiguration<UserEvent>
    {
        public void Configure(EntityTypeBuilder<UserEvent> entity)
        {
            entity.ToTable("USER_EVENT", "DCW");

            entity.Property(e => e.UserEventId).HasColumnName("USER_EVENT_ID");
            entity.Property(e => e.Detail)
            .HasMaxLength(1000)
            .IsUnicode(false)
            .HasColumnName("DETAIL");
            entity.Property(e => e.EndTime)
            .HasColumnType("datetime")
            .HasColumnName("END_TIME");
            entity.Property(e => e.EventType)
            .IsRequired()
            .HasMaxLength(10)
            .IsUnicode(false)
            .HasColumnName("EVENT_TYPE");
            entity.Property(e => e.StartTime)
            .HasColumnType("datetime")
            .HasColumnName("START_TIME");
            entity.Property(e => e.TaskId).HasColumnName("TASK_ID");
            entity.Property(e => e.TransactionId)
            .HasMaxLength(36)
            .IsUnicode(false)
            .HasColumnName("TRANSACTION_ID");
            entity.Property(e => e.Username)
            .IsRequired()
            .HasMaxLength(30)
            .IsUnicode(false)
            .HasColumnName("USERNAME");

            entity.HasOne(d => d.Task).WithMany(p => p.UserEvent)
            .HasForeignKey(d => d.TaskId)
            .OnDelete(DeleteBehavior.Cascade)
            .HasConstraintName("FK_TASK_USER_EVENT");

            entity.HasOne(d => d.UsernameNavigation).WithMany(p => p.UserEvent)
            .HasForeignKey(d => d.Username)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_USER_EVENT_USER_INFO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UserEvent> entity);
    }
}
