// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class UserInfoConfiguration : IEntityTypeConfiguration<UserInfo>
    {
        public void Configure(EntityTypeBuilder<UserInfo> entity)
        {
            entity.HasKey(e => e.Username);

            entity.ToTable("USER_INFO", "DCW");

            entity.Property(e => e.Username)
            .HasMaxLength(30)
            .IsUnicode(false)
            .HasColumnName("USERNAME");
            entity.Property(e => e.Fullname)
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasColumnName("FULLNAME");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UserInfo> entity);
    }
}
