// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class WorkflowCountyConfiguration : IEntityTypeConfiguration<WorkflowCounty>
    {
        public void Configure(EntityTypeBuilder<WorkflowCounty> entity)
        {
            entity.HasKey(e => e.CountyId);

            entity.ToTable("WORKFLOW_COUNTY", "DCW");

            entity.Property(e => e.CountyId).HasColumnName("COUNTY_ID");
            entity.Property(e => e.IsWorkflowActive).HasColumnName("IS_WORKFLOW_ACTIVE");

            entity.HasOne(d => d.County).WithOne(p => p.WorkflowCounty)
            .HasForeignKey<WorkflowCounty>(d => d.CountyId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_COUNTY_WORKFLOW_COUNTY");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WorkflowCounty> entity);
    }
}
