// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class WorkflowDataCenterConfiguration : IEntityTypeConfiguration<WorkflowDataCenter>
    {
        public void Configure(EntityTypeBuilder<WorkflowDataCenter> entity)
        {
            entity.HasKey(e => new { e.DataCenterId, e.EventTypeCode });

            entity.ToTable("WORKFLOW_DATA_CENTER", "DCW");

            entity.Property(e => e.DataCenterId).HasColumnName("DATA_CENTER_ID");
            entity.Property(e => e.EventTypeCode)
            .HasMaxLength(10)
            .IsUnicode(false)
            .HasColumnName("EVENT_TYPE_CODE");
            entity.Property(e => e.ReportFilePattern)
            .HasMaxLength(30)
            .IsUnicode(false)
            .HasColumnName("REPORT_FILE_PATTERN");

            entity.HasOne(d => d.DataCenter).WithMany(p => p.WorkflowDataCenter)
            .HasForeignKey(d => d.DataCenterId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_WORKFLOW_DATA_CENTER_DATA_CENTER");

            entity.HasOne(d => d.EventTypeCodeNavigation).WithMany(p => p.WorkflowDataCenter)
            .HasForeignKey(d => d.EventTypeCode)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_WORKFLOW_DATA_CENTER_EVENT_TYPE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WorkflowDataCenter> entity);
    }
}
