// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileImportExperiments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models.Configurations
{
    public partial class YearNumberReferenceConfiguration : IEntityTypeConfiguration<YearNumberReference>
    {
        public void Configure(EntityTypeBuilder<YearNumberReference> entity)
        {
            entity.ToTable("YEAR_NUMBER_REFERENCE");

            entity.Property(e => e.YearNumberReferenceId).HasColumnName("YEAR_NUMBER_REFERENCE_ID");
            entity.Property(e => e.CreateDate)
            .HasColumnType("datetime")
            .HasColumnName("CREATE_DATE");
            entity.Property(e => e.ImageBatchDocumentReferenceId).HasColumnName("IMAGE_BATCH_DOCUMENT_REFERENCE_ID");
            entity.Property(e => e.RecordingNumber)
            .HasMaxLength(10)
            .IsUnicode(false)
            .IsFixedLength()
            .HasColumnName("RECORDING_NUMBER");
            entity.Property(e => e.RecordingYear)
            .HasMaxLength(4)
            .IsUnicode(false)
            .IsFixedLength()
            .HasColumnName("RECORDING_YEAR");
            entity.Property(e => e.SeriesCode)
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasColumnName("SERIES_CODE");
            entity.Property(e => e.Source)
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasColumnName("SOURCE");
            entity.Property(e => e.Suffix)
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasColumnName("SUFFIX");
            entity.Property(e => e.UpdateDate)
            .HasColumnType("datetime")
            .HasColumnName("UPDATE_DATE");

            entity.HasOne(d => d.ImageBatchDocumentReference).WithMany(p => p.YearNumberReference)
            .HasForeignKey(d => d.ImageBatchDocumentReferenceId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_YEAR_NUMBER_REFERENCE_IMAGE_BATCH_DOCUMENT_REFERENCE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<YearNumberReference> entity);
    }
}
