// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models;

public partial class BatchStatus
{
    public byte BatchStatusId { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Batch> Batch { get; set; } = new List<Batch>();
}