// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models;

public partial class Batch
{
    public long BatchId { get; set; }

    public string Reference { get; set; }

    public string Notes { get; set; }

    public byte BatchStatusId { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public byte CountyId { get; set; }

    public virtual BatchStatus BatchStatus { get; set; }

    public virtual County County { get; set; }

    public virtual ICollection<DocumentDescription> DocumentDescription { get; set; } = new List<DocumentDescription>();
}