// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models;

public partial class BookPageReference
{
    public long BookPageReferenceId { get; set; }

    public string Source { get; set; }

    public string Book { get; set; }

    public string BookSuffix { get; set; }

    public string Page { get; set; }

    public string PageSuffix { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public long ImageBatchDocumentReferenceId { get; set; }

    public virtual ImageBatchDocumentReference ImageBatchDocumentReference { get; set; }
}