// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models;

public partial class ClerkNumberTracking
{
    public byte CountyId { get; set; }

    public string ClerkNumber { get; set; }
}