// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models;

public partial class CngapResults
{
    public long? ClerkNumberGapFromCn { get; set; }

    public long? ClerkNumberGapToCn { get; set; }

    public long? ClerkNumberGapCount { get; set; }
}