// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models;

public partial class County
{
    public byte CountyId { get; set; }

    public string CountyName { get; set; }

    public string CountyCode { get; set; }

    public int? Priority { get; set; }

    public bool? IsActive { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public long DataCenterId { get; set; }

    public virtual ICollection<Batch> Batch { get; set; } = new List<Batch>();

    public virtual ICollection<CountyArchivePath> CountyArchivePath { get; set; } = new List<CountyArchivePath>();

    public virtual ICollection<CountyFtpPath> CountyFtpPath { get; set; } = new List<CountyFtpPath>();

    public virtual DataCenter DataCenter { get; set; }

    public virtual ICollection<DateOfFile> DateOfFile { get; set; } = new List<DateOfFile>();

    public virtual ICollection<Event> Event { get; set; } = new List<Event>();

    public virtual ICollection<PerformanceTarget> PerformanceTarget { get; set; } = new List<PerformanceTarget>();

    public virtual WorkflowCounty WorkflowCounty { get; set; }
}