// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models;

public partial class DataCenter
{
    public long DataCenterId { get; set; }

    public string Name { get; set; }

    public string Code { get; set; }

    public virtual ICollection<County> County { get; set; } = new List<County>();

    public virtual ICollection<OnDemandReportPath> OnDemandReportPath { get; set; } = new List<OnDemandReportPath>();

    public virtual ICollection<WorkflowDataCenter> WorkflowDataCenter { get; set; } = new List<WorkflowDataCenter>();
}