// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models;

public partial class DocumentDescriptionRcvd
{
    public long DocumentDescriptionRcvdId { get; set; }

    public DateTime DateReceived { get; set; }

    public long DocumentDescriptionId { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public long ImageBatchId { get; set; }

    public virtual DocumentDescription DocumentDescription { get; set; }

    public virtual ImageBatch ImageBatch { get; set; }
}