// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models;

public partial class DocumentDescription
{
    public long DocumentDescriptionId { get; set; }

    public long BatchId { get; set; }

    public string PrimaryReference { get; set; }

    public string SecondaryReference { get; set; }

    public string State { get; set; }

    public string County { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public DateTime DateOfFile { get; set; }

    public virtual Batch Batch { get; set; }

    public virtual ICollection<DocumentDescriptionRcvd> DocumentDescriptionRcvd { get; set; } = new List<DocumentDescriptionRcvd>();

    public virtual ICollection<PostingAttempt> PostingAttempt { get; set; } = new List<PostingAttempt>();
}