// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models;

public partial class Event
{
    public long EventId { get; set; }

    public long? DateOfFileId { get; set; }

    public string EventTypeCode { get; set; }

    public string ReportFileName { get; set; }

    public byte? CountyId { get; set; }

    public byte Priority { get; set; }

    public virtual County County { get; set; }

    public virtual DateOfFile DateOfFile { get; set; }

    public virtual EventType EventTypeCodeNavigation { get; set; }

    public virtual ICollection<Task> Task { get; set; } = new List<Task>();
}