// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models;

public partial class GetNewWorkLock
{
    public string Username { get; set; }

    public DateTime StartTime { get; set; }
}