// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models;

public partial class ImageBatchDocumentReference
{
    public long ImageBatchDocumentReferenceId { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public virtual ICollection<BookPageReference> BookPageReference { get; set; } = new List<BookPageReference>();

    public virtual ICollection<ImageBatch> ImageBatchBeginningImageBatchDocumentReference { get; set; } = new List<ImageBatch>();

    public virtual ICollection<ImageBatch> ImageBatchEndingImageBatchDocumentReference { get; set; } = new List<ImageBatch>();

    public virtual ICollection<YearNumberReference> YearNumberReference { get; set; } = new List<YearNumberReference>();
}