// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models;

public partial class ImageBatchFtpUpload
{
    public long ImageBatchFtpUploadId { get; set; }

    public DateTime FtpUploadDate { get; set; }

    public int CountyFtpPathId { get; set; }

    public long ImageBatchId { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public virtual ImageBatch ImageBatch { get; set; }
}