// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models;

public partial class OnDemandReportPath
{
    public long OnDemandReportPathId { get; set; }

    public string OnDemandReportPath1 { get; set; }

    public long DataCenterId { get; set; }

    public long OnDemandReportId { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public virtual DataCenter DataCenter { get; set; }

    public virtual OnDemandReport OnDemandReport { get; set; }
}