// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models;

public partial class OnDemandReport
{
    public long OnDemandReportId { get; set; }

    public string ReportName { get; set; }

    public string SourceFileKey { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public virtual ICollection<OnDemandReportPath> OnDemandReportPath { get; set; } = new List<OnDemandReportPath>();
}