// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models;

public partial class PerformanceTarget
{
    public long PerformanceTargetId { get; set; }

    public byte ProcessingUnitId { get; set; }

    public int NumberOfHours { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public byte CountyId { get; set; }

    public bool IsActive { get; set; }

    public virtual County County { get; set; }

    public virtual ProcessingUnit ProcessingUnit { get; set; }
}