// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models;

public partial class PostingAttemptStatus
{
    public byte PostingAttemptStatusId { get; set; }

    public string Description { get; set; }

    public virtual ICollection<PostingAttempt> PostingAttempt { get; set; } = new List<PostingAttempt>();
}