// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models;

public partial class ProcessingUnit
{
    public byte ProcessingUnitId { get; set; }

    public string ProcessingUnitName { get; set; }

    public string ProcessingUnitCode { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public virtual ICollection<NonWeekendHoliday> NonWeekendHoliday { get; set; } = new List<NonWeekendHoliday>();

    public virtual ICollection<PerformanceTarget> PerformanceTarget { get; set; } = new List<PerformanceTarget>();

    public virtual ICollection<WorkDay> WorkDay { get; set; } = new List<WorkDay>();
}