// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models;

public partial class TaskType
{
    public string TaskTypeCode { get; set; }

    public string TaskTypeDescription { get; set; }

    public bool Selectable { get; set; }

    public virtual ICollection<Task> Task { get; set; } = new List<Task>();
}