// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models;

public partial class Task
{
    public long TaskId { get; set; }

    public string TaskTypeCode { get; set; }

    public long EventId { get; set; }

    public bool? Assigned { get; set; }

    public bool? Complete { get; set; }

    public string CompletedBy { get; set; }

    public bool? Verified { get; set; }

    public string VerifiedSource { get; set; }

    public virtual UserInfo CompletedByNavigation { get; set; }

    public virtual Event Event { get; set; }

    public virtual ICollection<TaskDetail> TaskDetail { get; set; } = new List<TaskDetail>();

    public virtual TaskType TaskTypeCodeNavigation { get; set; }

    public virtual ICollection<UserEvent> UserEvent { get; set; } = new List<UserEvent>();
}