// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models;

public partial class UserInfo
{
    public string Username { get; set; }

    public string Fullname { get; set; }

    public virtual ICollection<Task> Task { get; set; } = new List<Task>();

    public virtual ICollection<UserEvent> UserEvent { get; set; } = new List<UserEvent>();
}