// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models;

public partial class UserEvent
{
    public long UserEventId { get; set; }

    public string Username { get; set; }

    public string EventType { get; set; }

    public long? TaskId { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public string Detail { get; set; }

    public string TransactionId { get; set; }

    public virtual Task Task { get; set; }

    public virtual UserInfo UsernameNavigation { get; set; }
}