// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models;

public partial class WorkflowCounty
{
    public byte CountyId { get; set; }

    public bool IsWorkflowActive { get; set; }

    public virtual County County { get; set; }
}