// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models;

public partial class WorkflowDataCenter
{
    public long DataCenterId { get; set; }

    public string EventTypeCode { get; set; }

    public string ReportFilePattern { get; set; }

    public virtual DataCenter DataCenter { get; set; }

    public virtual EventType EventTypeCodeNavigation { get; set; }
}