// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileImportExperiments.Models;

public partial class YearNumberReference
{
    public long YearNumberReferenceId { get; set; }

    public string Source { get; set; }

    public string RecordingYear { get; set; }

    public string RecordingNumber { get; set; }

    public string Suffix { get; set; }

    public string SeriesCode { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public long ImageBatchDocumentReferenceId { get; set; }

    public virtual ImageBatchDocumentReference ImageBatchDocumentReference { get; set; }
}